"""empty message

Revision ID: ea4269013406
Revises: 
Create Date: 2023-11-28 21:43:23.916326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4269013406'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Brands',
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['Goods.good_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('brand_id')
    )
    op.create_index(op.f('ix_Brands_brand_id'), 'Brands', ['brand_id'], unique=True)
    op.create_table('Goods',
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('new_price', sa.Integer(), nullable=True),
    sa.Column('old_price', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=10000), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['Brands.brand_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('good_id')
    )
    op.create_index(op.f('ix_Goods_good_id'), 'Goods', ['good_id'], unique=True)
    op.create_table('Category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['Goods.good_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_index(op.f('ix_Category_category_id'), 'Category', ['category_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Category_category_id'), table_name='Category')
    op.drop_table('Category')
    op.drop_index(op.f('ix_Goods_good_id'), table_name='Goods')
    op.drop_table('Goods')
    op.drop_index(op.f('ix_Brands_brand_id'), table_name='Brands')
    op.drop_table('Brands')
    # ### end Alembic commands ###
